DROP DATABASE solutech
CREATE DATABASE solutech

USE solutech

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR (75) NOT NULL UNIQUE,
    password VARCHAR(1000) NOT NULL
)

ALTER TABLE users ADD COLUMN role ENUM('user', 'admin') NOT NULL DEFAULT 'user';